@startuml UC_Sprint5_Historique
title UC — Sprint 5 : Historique & Visualisation
skinparam backgroundColor white
skinparam defaultFontName Arial
skinparam monochrome true
skinparam shadowing false

' ── Taille pour impression ──────────────

skinparam defaultFontSize 16
skinparam usecaseFontSize 16
skinparam actorFontSize 18
skinparam packageFontSize 18
skinparam noteFontSize 14
skinparam ArrowFontSize 14
skinparam usecaseBorderThickness 2
skinparam actorBorderThickness 2.5
skinparam ArrowThickness 2
skinparam nodesep 60
skinparam ranksep 80


left to right direction

actor Utilisateur as U

rectangle "Sprint 5 — Historique & Visualisation" {
  usecase "Consulter l'historique\nd'irrigation (paginé)" as UC1
  usecase "Consulter le détail\nd'une entrée" as UC5
  usecase "Exporter en CSV" as UC6
}

U --> UC1
U --> UC5
U --> UC6
@enduml