@startuml UC_Sprint1_Authentification
title UC — Sprint 1 : Authentification & Gestion Utilisateur
skinparam backgroundColor white
skinparam defaultFontName Arial
skinparam monochrome true
skinparam shadowing false

' ── Taille pour impression ──────────────

skinparam defaultFontSize 16
skinparam usecaseFontSize 16
skinparam actorFontSize 18
skinparam packageFontSize 18
skinparam noteFontSize 14
skinparam ArrowFontSize 14
skinparam usecaseBorderThickness 2
skinparam actorBorderThickness 2.5
skinparam ArrowThickness 2
skinparam nodesep 60
skinparam ranksep 80


left to right direction

actor Utilisateur as U
actor "Google\nOAuth 2.0" as G

rectangle "Sprint 1 — Authentification" {
  usecase "S'inscrire\n(email + mot de passe)" as UC1
  usecase "Valider le formulaire" as UC1a
  usecase "Se connecter par email" as UC2
  usecase "Vérifier les identifiants" as UC2a
  usecase "Se connecter via Google" as UC3
  usecase "Réinitialiser le mot de passe\n(OTP par email)" as UC4
  usecase "Vérifier le code OTP" as UC4a
  usecase "Se déconnecter" as UC5
  usecase "Modifier le profil\n(FR / EN / AR / TR)" as UC6
}

U --> UC1
UC1 ..> UC1a : <<include>>
U --> UC2
UC2 ..> UC2a : <<include>>
U --> UC3
UC3 --> G
U --> UC4
UC4 ..> UC4a : <<include>>
U --> UC5
U --> UC6
@enduml
